// PDF tool definitions (Phase 2). 18 tools: conversions via poppler,
// LibreOffice, pdfjs + office libs, and direct PDF edits via pdf-lib,
// Ghostscript, qpdf and Tesseract.
import type { ToolDefinition } from '../toolRegistry';

const PDF = 'application/pdf';
const DOC = 'application/msword';
const DOCX =
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const XLS = 'application/vnd.ms-excel';
const XLSX =
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const PPT = 'application/vnd.ms-powerpoint';
const PPTX =
  'application/vnd.openxmlformats-officedocument.presentationml.presentation';

export const PDF_TOOLS: ToolDefinition[] = [
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    category: 'pdf',
    tagline: 'Turn every PDF page into a JPG or PNG image.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'format',
        label: 'Image format',
        type: 'select',
        default: 'jpg',
        options: [
          { value: 'jpg', label: 'JPG' },
          { value: 'png', label: 'PNG' },
        ],
      },
      {
        name: 'dpi',
        label: 'Resolution (DPI)',
        type: 'select',
        default: '150',
        options: [
          { value: '150', label: '150 DPI' },
          { value: '300', label: '300 DPI' },
        ],
        help: 'Higher DPI gives sharper images but larger files.',
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    category: 'pdf',
    tagline: 'Extract PDF text into an editable Word document.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [],
    enabled: true,
    phase: 2,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    category: 'pdf',
    tagline: 'Convert DOC and DOCX files to PDF.',
    inputMimes: [DOC, DOCX],
    inputExts: ['doc', 'docx'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [],
    enabled: true,
    phase: 2,
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    category: 'pdf',
    tagline: 'Pull PDF text into a spreadsheet, page by page.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [],
    enabled: true,
    phase: 2,
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    category: 'pdf',
    tagline: 'Convert XLS and XLSX spreadsheets to PDF.',
    inputMimes: [XLS, XLSX],
    inputExts: ['xls', 'xlsx'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [],
    enabled: true,
    phase: 2,
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    category: 'pdf',
    tagline: 'Turn each PDF page into a presentation slide.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [],
    enabled: true,
    phase: 2,
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    category: 'pdf',
    tagline: 'Convert PPT and PPTX presentations to PDF.',
    inputMimes: [PPT, PPTX],
    inputExts: ['ppt', 'pptx'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [],
    enabled: true,
    phase: 2,
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    category: 'pdf',
    tagline: 'Combine up to 20 PDFs into one file, in order.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 20,
    optionsSchema: [],
    enabled: true,
    phase: 2,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    category: 'pdf',
    tagline: 'Extract page ranges into separate PDF files.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'ranges',
        label: 'Page ranges',
        type: 'text',
        required: true,
        placeholder: '1-3, 5',
        help: 'Page ranges to extract, e.g. 1-3, 5, 8-10. Each range becomes its own PDF.',
        maxLength: 200,
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    category: 'pdf',
    tagline: 'Shrink PDF file size with three quality levels.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'quality',
        label: 'Quality',
        type: 'select',
        default: 'ebook',
        options: [
          { value: 'screen', label: 'Smaller size' },
          { value: 'ebook', label: 'Balanced' },
          { value: 'printer', label: 'High quality' },
        ],
        help: 'Smaller size compresses more aggressively; High quality keeps print-ready detail.',
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    category: 'pdf',
    tagline: 'Rotate pages by 90, 180 or 270 degrees.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'angle',
        label: 'Rotation angle',
        type: 'select',
        default: '90',
        options: [
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '270° clockwise' },
        ],
      },
      {
        name: 'pages',
        label: 'Pages',
        type: 'text',
        default: 'all',
        placeholder: 'all',
        help: 'Type "all", or specific pages e.g. 1, 3-5.',
        maxLength: 200,
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    category: 'pdf',
    tagline: 'Lock a PDF with a password (128-bit encryption).',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
        maxLength: 64,
        help: 'Anyone opening the PDF will need this password.',
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    category: 'pdf',
    tagline: 'Remove the password from a PDF you own.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'password',
        label: 'Current password (if any)',
        type: 'text',
        maxLength: 64,
        help: 'Leave blank if the PDF opens without a password.',
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    category: 'pdf',
    tagline: 'Stamp diagonal text across every page.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'text',
        label: 'Watermark text',
        type: 'text',
        required: true,
        default: 'CONFIDENTIAL',
        maxLength: 60,
      },
      {
        name: 'opacity',
        label: 'Opacity',
        type: 'number',
        min: 10,
        max: 60,
        default: 25,
        help: 'Percent — 10 is faint, 60 is bold.',
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'page-numbers-pdf',
    name: 'Add Page Numbers',
    category: 'pdf',
    tagline: 'Stamp page numbers onto every page.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'position',
        label: 'Position',
        type: 'select',
        default: 'bottom-center',
        options: [
          { value: 'bottom-center', label: 'Bottom center' },
          { value: 'bottom-right', label: 'Bottom right' },
          { value: 'top-center', label: 'Top center' },
        ],
      },
      {
        name: 'startAt',
        label: 'Start numbering at',
        type: 'number',
        min: 1,
        max: 100000,
        default: 1,
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    category: 'pdf',
    tagline: 'Make scanned PDFs searchable with text recognition.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'language',
        label: 'Document language',
        type: 'select',
        default: 'eng',
        options: [{ value: 'eng', label: 'English' }],
      },
    ],
    enabled: true,
    phase: 2,
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    category: 'pdf',
    tagline: 'Extract all text from a PDF into a plain .txt file.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [],
    enabled: true,
    phase: 2,
  },
  {
    id: 'reorder-pdf',
    name: 'Reorder PDF Pages',
    category: 'pdf',
    tagline: 'Rearrange pages into any order you choose.',
    inputMimes: [PDF],
    inputExts: ['pdf'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'order',
        label: 'New page order',
        type: 'text',
        required: true,
        placeholder: '3, 1, 2',
        help: 'Comma-separated page numbers in the order you want them. List every page once.',
        maxLength: 2000,
      },
    ],
    enabled: true,
    phase: 2,
  },
];
