// Utility tool definitions (Phase 5): QR codes, text stats, hashtag sets, social resizers.
import type { ToolDefinition } from '../toolRegistry';

export const UTILITY_TOOLS: ToolDefinition[] = [
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    category: 'utility',
    tagline: 'Turn any link or text into a scannable QR code image.',
    inputMimes: [],
    inputExts: [],
    requiresFile: false,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'text',
        label: 'Link or text',
        type: 'textarea',
        required: true,
        maxLength: 2000,
        placeholder: 'https://example.com',
        help: 'The content encoded into the QR code.',
      },
      {
        name: 'size',
        label: 'Image size (px)',
        type: 'select',
        default: '512',
        options: [
          { value: '256', label: '256 px' },
          { value: '512', label: '512 px' },
          { value: '1024', label: '1024 px' },
        ],
      },
    ],
    enabled: true,
    phase: 5,
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    category: 'utility',
    tagline: 'Count words, characters, sentences and paragraphs instantly.',
    inputMimes: [],
    inputExts: [],
    requiresFile: false,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'text',
        label: 'Paste your text',
        type: 'textarea',
        required: true,
        maxLength: 20000,
        placeholder: 'Paste or type your text here…',
        help: 'Up to 20,000 characters.',
      },
    ],
    enabled: true,
    phase: 5,
  },
  {
    id: 'hashtag-generator',
    name: 'Hashtag Generator',
    category: 'utility',
    tagline: 'Get a curated set of hashtags for your topic and platform.',
    inputMimes: [],
    inputExts: [],
    requiresFile: false,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'topic',
        label: 'Topic',
        type: 'text',
        required: true,
        maxLength: 80,
        placeholder: 'e.g. homemade pizza',
        help: 'A few words describing your post.',
      },
      {
        name: 'platform',
        label: 'Platform',
        type: 'select',
        default: 'instagram',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'youtube', label: 'YouTube' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'x', label: 'X' },
        ],
      },
      {
        name: 'count',
        label: 'Number of hashtags',
        type: 'number',
        default: 15,
        min: 5,
        max: 30,
        step: 1,
      },
    ],
    enabled: true,
    phase: 5,
  },
  {
    id: 'social-resizer',
    name: 'Social Media Image Resizer',
    category: 'utility',
    tagline: 'Resize any photo to the perfect size for each social platform.',
    inputMimes: ['image/jpeg', 'image/png', 'image/webp'],
    inputExts: ['.jpg', '.jpeg', '.png', '.webp'],
    requiresFile: true,
    maxFiles: 1,
    optionsSchema: [
      {
        name: 'preset',
        label: 'Platform preset',
        type: 'select',
        default: 'instagram-post',
        options: [
          { value: 'instagram-post', label: 'Instagram Post — 1080×1080' },
          { value: 'instagram-story', label: 'Instagram Story — 1080×1920' },
          { value: 'youtube-thumbnail', label: 'YouTube Thumbnail — 1280×720' },
          { value: 'facebook-post', label: 'Facebook Post — 1200×630' },
          { value: 'x-post', label: 'X Post — 1200×675' },
        ],
        help: 'The image is cropped to fill the exact dimensions.',
      },
    ],
    enabled: true,
    phase: 5,
  },
];
